# Copyright 2020 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# [START istio_proxy_telemetry_operations_suite_wi_istio_operator]
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  profile: empty
  tag: $ISTIO_VERSION-distroless
  components:
    base:
      enabled: true
    pilot:
      enabled: true
      k8s:
        overlays:
        - apiVersion: v1
          kind: ServiceAccount
          name: istio-pilot-service-account
          patches:
          - path: metadata.annotations
            value:
              iam.gke.io/gcp-service-account: istio-proxy-telemetry-system@$GOOGLE_CLOUD_PROJECT.iam.gserviceaccount.com
    ingressGateways:
    - enabled: true
      k8s:
        overlays:
        - apiVersion: v1
          kind: ServiceAccount
          name: istio-ingressgateway-service-account
          patches:
          - path: metadata.annotations
            value:
              iam.gke.io/gcp-service-account: istio-proxy-telemetry-system@$GOOGLE_CLOUD_PROJECT.iam.gserviceaccount.com
  values:
    global:
      enableTracing: true
      proxy:
        excludeIPRanges: 169.254.169.254/32 # metadata server
        tracer: stackdriver
    pilot:
      traceSampling: 100.0 # sample 100%, do not use this value for production
    telemetry:
      enabled: true
      v2:
        enabled: true
        prometheus:
          enabled: false
        stackdriver:
          enabled: true
          logging: true
          monitoring: true
# [END istio_proxy_telemetry_operations_suite_wi_istio_operator]
